packages:
  ICT.BASE:
    url: https://github.com/Innovative-Cloud-Technologies/esphome-configs
    file: ict-base.yaml
    refresh: 1min

esphome:
  project:
    name: "ICT.PLF12"
    version: "1.1.9"

dashboard_import:
  package_import_url: github://Innovative-Cloud-Technologies/esphome-configs/ict-plf12.yaml@main

substitutions:
  voltage_divider_val:  "2001"
  hlw_model:         BL0937
  current_resistor_val: "0.001"
  power_cal_val1_in:    "0.0"
  power_cal_val1_out:   "0.0"
  power_cal_val2_in:    "879.4"
  power_cal_val2_out:   "750"
  current_cal_val1_in:  "0.0"
  current_cal_val1_out: "0.0"
  current_cal_val2_in:  "6.8"
  current_cal_val2_out: "3.5"
  voltage_cal_val1_in:  "0.0"
  voltage_cal_val1_out: "0.0"
  voltage_cal_val2_in:  "132.7"
  voltage_cal_val2_out: "119.1"
  change_mode_every: "1"
  update_interval: 10s
  initial_mode: CURRENT
  # GPIO definitions
  red_led_pin:  GPIO1
  button_pin:   GPIO3
  pm_cf_pin:    GPIO4
  pm_cf1_pin:   GPIO5
  blue_led_pin: GPIO12
  relay_pin:    GPIO13
  pm_sel_pin:   GPIO14

esp8266:
  board: esp01_1m
  restore_from_flash: true
  early_pin_init: false

status_led:
    pin:
      number: $red_led_pin
      inverted: true

output:
  - platform: gpio
    id: blue_led
    pin:
      number: $blue_led_pin
      inverted: true

switch:
  - platform: gpio
    id: relay
    name: $entity_name
    pin: $relay_pin
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - output.turn_on: blue_led
    on_turn_off:
      - output.turn_off: blue_led

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: $button_pin
      inverted: true
      mode:
        input: true
        pullup: true
    filters:
      - delayed_on: 50ms
    on_press:
      then:
        switch.toggle: relay

sensor:
  - platform: hlw8012
    id: hlw_main
    sel_pin:
      number: $pm_sel_pin
      inverted: True
    cf_pin: $pm_cf_pin
    cf1_pin: $pm_cf1_pin
    current_resistor: $current_resistor_val
    voltage_divider: $voltage_divider_val
    change_mode_every: $change_mode_every
    update_interval: $update_interval
    initial_mode: $initial_mode
    model: $hlw_model
    power:
      name: $display-name Power
      unit_of_measurement: W
      id: wattage
      filters:
        - calibrate_linear:
            - $power_cal_val1_in -> $power_cal_val1_out
            - $power_cal_val2_in -> $power_cal_val2_out
    current:
      name: $entity_name Current
      unit_of_measurement: A
      id: current
      filters:
        - calibrate_linear:
            - $current_cal_val1_in -> $current_cal_val1_out
            - $current_cal_val2_in -> $current_cal_val2_out
    voltage:
      name: $entity_name Voltage
      unit_of_measurement: V
      id: voltage
      filters:
        - calibrate_linear:
            - $voltage_cal_val1_in -> $voltage_cal_val1_out
            - $voltage_cal_val2_in -> $voltage_cal_val2_out

  - platform: total_daily_energy
    name: $entity_name Total Daily Energy
    power_id: wattage
    filters:
        - multiply: 0.001  ## convert Wh to kWh
    unit_of_measurement: kWh