esphome:
  name: $entity_name
  friendly_name: $friendly_name
  project:
    name: "ICT.BASE"
    version: "0.0.6"
  on_boot:
    - lambda: |-
        id(my_ota).set_auth_password("7377477570");    
    
dashboard_import:
  package_import_url: github://Innovative-Cloud-Technologies/esphome-configs/ict-base.yaml@main
    
wifi:
  ssid: $SSID
  password: $Wifi_PW
  fast_connect: True
  ap:
    ssid: $friendly_name
    password: $Wifi_PW
    ap_timeout: 5min   
ota:
  - platform: esphome
    id: my_ota
    password: $ota
    
web_server:
  port: 80
  version: 3
  ota: true
  
api:
logger:

sensor:
  - platform: wifi_signal
    name: WiFi Signal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

button:
  - platform: restart
    id: restart_button
    name: Restart
    entity_category: diagnostic
