esphome:
  name: $device_name
  project:
    name: "ICT.BASE"
    version: "0.0.4"

dashboard_import:
  package_import_url: github://Innovative-Cloud-Technologies/esphome-configs/ict-base.yaml@main

substitutions:
  device_name: ict-base
  entity_name: "ICT Base"

wifi:
  fast_connect: True
  ap:
    ssid: $device_name
    password: $device_name

web_server:
  include_internal: true

ota:
  password: 12345678

api:
captive_portal:
logger:

time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: wifi_signal
    name: $display-name WiFi Signal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $display-name IP Address