esphome:
  name: $entity_name
  friendly_name: $friendly_name
  project:
    name: "ICT.BASE"
    version: "0.0.6"
    
dashboard_import:
  package_import_url: github://Innovative-Cloud-Technologies/esphome-configs/ict-base.yaml@main
  
substitutions:
  SSID: "!secret wifi_ssid"
  Password: "!secret wifi_password"
  
wifi:
  ssid: $SSID
  password: $Password
  fast_connect: True
  ap:
    ssid: $friendly_name
    password: "12345678"
    ap_timeout: 5min   

ota:
  - platform: esphome
    password: 12345678

web_server:
  port: 80
  version: 3
  ota: true
  
api:
logger:

sensor:
  - platform: wifi_signal
    name: WiFi Signal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

button:
  - platform: restart
    id: restart_button
    name: Restart
    entity_category: diagnostic
