esphome:
  name: $device_name
  project:
    name: "ICT.BASE"
    version: "0.0.6"

dashboard_import:
  package_import_url: github://Innovative-Cloud-Technologies/esphome-configs/ict-base.yaml@main

substitutions:
  device_name: ict-base
  entity_name: "ICT Base"

wifi:
  fast_connect: True
  ap:
    ssid: $device_name
    password: "12345678"

ota:
  - platform: esphome
    password: 12345678

web_server:
  port: 80
  version: 3
  ota: true
  
api:
captive_portal:
logger:

sensor:
  - platform: wifi_signal
    name: $entity_name WiFi Signal

text_sensor:
  - platform: wifi_info
    ip_address:
      name: $entity_name IP Address

button:
  - platform: restart
    id: restart_button
    name: Restart Device
    entity_category: diagnostic
